/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodmood.analytics;

/**
 *
 * @author Dylan
 */
public class analyticAppUI extends javax.swing.JPanel {

    /**
     * Creates new form analyticAppUI
     */
    public analyticAppUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodHistoryButton = new javax.swing.JButton();
        moodHistoryButton = new javax.swing.JButton();
        correlationButton = new javax.swing.JButton();
        chartingButton = new javax.swing.JButton();

        foodHistoryButton.setText("View Food History");
        foodHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodHistoryButtonActionPerformed(evt);
            }
        });

        moodHistoryButton.setText("View Mood History");

        correlationButton.setText("Correlations");

        chartingButton.setText("Charting");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foodHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moodHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(correlationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chartingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(foodHistoryButton)
                .addGap(18, 18, 18)
                .addComponent(moodHistoryButton)
                .addGap(18, 18, 18)
                .addComponent(correlationButton)
                .addGap(18, 18, 18)
                .addComponent(chartingButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void foodHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodHistoryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chartingButton;
    private javax.swing.JButton correlationButton;
    private javax.swing.JButton foodHistoryButton;
    private javax.swing.JButton moodHistoryButton;
    // End of variables declaration//GEN-END:variables
}
