/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodmood.analytics;

/**
 *
 * @author Dylan
 */
public class appPickerUI extends javax.swing.JPanel {

    /**
     * Creates new form appPickerUI
     */
    public appPickerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mobileAppButton = new javax.swing.JButton();
        analyticsAppButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        mobileAppButton.setText("Mobile App");
        mobileAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileAppButtonActionPerformed(evt);
            }
        });

        analyticsAppButton.setText("Analytic App");
        analyticsAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyticsAppButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Select which app you would like to launch....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(analyticsAppButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mobileAppButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(mobileAppButton)
                .addGap(18, 18, 18)
                .addComponent(analyticsAppButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void analyticsAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyticsAppButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analyticsAppButtonActionPerformed

    private void mobileAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileAppButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileAppButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyticsAppButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mobileAppButton;
    // End of variables declaration//GEN-END:variables
}
